// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckoutBranch(arg1, arg2) {
  return window['go']['main']['App']['CheckoutBranch'](arg1, arg2);
}

export function CheckoutRemoteBranch(arg1, arg2) {
  return window['go']['main']['App']['CheckoutRemoteBranch'](arg1, arg2);
}

export function GetBranches(arg1) {
  return window['go']['main']['App']['GetBranches'](arg1);
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function OpenRepository(arg1, arg2) {
  return window['go']['main']['App']['OpenRepository'](arg1, arg2);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickIdeaExecutable() {
  return window['go']['main']['App']['PickIdeaExecutable']();
}

export function RefreshRepository(arg1) {
  return window['go']['main']['App']['RefreshRepository'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanRepositories(arg1, arg2) {
  return window['go']['main']['App']['ScanRepositories'](arg1, arg2);
}

export function UpdateRepositories(arg1) {
  return window['go']['main']['App']['UpdateRepositories'](arg1);
}
